name: Java CI/CD with Maven

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:  # Job ID
    name: Java CI/CD with Maven  # Name of the job
    runs-on: ubuntu-latest

    steps:
      # Check out the repository code
      - uses: actions/checkout@v4

      # Set up JDK 17 environment
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      # Build and run tests
      - name: Build with Maven and run tests
        run: mvn -B clean verify
